export default {
  classes: true,
  reset: false,
  borders: {
    radii: [2, 4, 8, 9999],
    widths: [1, 2, 4],
  },
  breakpoints: {
    lg: '48em',
  },
  fonts: {
    sans: 'system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif',
    serif: 'Georgia, Cambria, Times New Roman, Times, serif',
    mono: 'Source Code Pro, Roboto Mono, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
  },
  grid: {
    steps: 6,
  },
  spaceScale: {
    steps: 6,
    viewportMin: 320,
    viewportMax: 1500,
    baseMin: 16,
    baseMax: 18,
    scaleMin: 'minor-third',
    scaleMax: 'perfect-fourth',
  },
  typeScale: {
    steps: 6,
    viewportMin: 320,
    viewportMax: 1500,
    baseMin: 16,
    baseMax: 18,
    scaleMin: 'minor-third',
    scaleMax: 'perfect-fourth',
  },
  color: {
    scales: {
      gray: "#808080"
    },
    spots: {
      "e-color-gray-1": "var(--gray100)",
      "e-color-gray-2": "var(--gray200)",
      "e-color-gray-3": "var(--gray300)",
      "e-color-gray-4": "var(--gray400)",
      "e-color-gray-5": "var(--gray500)",
      "e-color-gray-6": "var(--gray600)",
      "e-color-gray-7": "var(--gray700)",
      "e-color-gray-8": "var(--gray800)",
      "e-color-gray-9": "var(--gray900)",

      "e-color-info-1": "#d8ebfe",
      "e-color-info-2": "#6990ee",
      "e-color-info-3": "#494eaa",
      "e-color-warning-1": "#fce2de",
      "e-color-warning-2": "#e36f4f",
      "e-color-warning-3": "#a2204f",
      "e-color-success-1": "#ccf3ca",
      "e-color-success-2": "#26a573",
      "e-color-success-3": "#146146",
      "e-color-error-1": "#f6e5bb",
      "e-color-error-2": "#eb6176",
      "e-color-error-3": "#963712",
      "e-header-bg-color": "var(--e-color-gray-1)",
      "e-header-color": "currentColor",

      "e-color-disabled-fg": "var(--e-color-gray-4)",
      "e-color-disabled-bg": "var(--e-color-gray-1)",
      "e-color-focus": "var(--e-color-info-1)",
      "e-color-primary-action": "#157bb6",
      "e-color-primary-bg": "white",
      "e-color-border": "var(--e-color-gray-2)",
    },
  },
  customProperties: {
    "e-border-radius-sm": "var(--borderRadius0)",
    "e-border-radius-md": "var(--borderRadius1)",
    "e-border-radius-full": "var(--borderRadius3)",
    "e-max-content-width": "1320px",
    "e-input-min-height": "var(--space4)",
    "e-target-min-size": "var(--space2)",
    "e-space-xs": "var(--space-4)",
    "e-space-sm": "var(--space-1)",
    "e-space-md": "var(--space0)",
    "e-space-lg": "var(--space3)",
    "e-space-xl": "var(--space5)",
    "e-font-size-min": "var(--text-1)",
    "e-font-size-default": "var(--text0)",
    "e-font-size-md": "var(--text1)",
    "e-font-size-lg": "var(--text3)",
    "e-font-size-xl": "var(--text4)",
    "e-header-height": "3rem",
  },
}
