/**
 *
 * https://api.nhle.com/stats/rest/en/skater/summary?isAggregate=false&isGame=false&sort=[{%22property%22:%22points%22,%22direction%22:%22DESC%22},{%22property%22:%22gamesPlayed%22,%22direction%22:%22ASC%22},{%22property%22:%22playerId%22,%22direction%22:%22ASC%22}]&start=0&limit=50&factCayenneExp=gamesPlayed%3E=1&cayenneExp=gameTypeId=2%20and%20seasonId%3C=20232024%20and%20seasonId%3E=20232024
 */

export function get(req) {
  const { sort = 'points', position = 'all' } = req.query
  const data = [
      {
        "assists": 100,
        "evGoals": 31,
        "evPoints": 91,
        "faceoffWinPct": 0.5,
        "gameWinningGoals": 6,
        "gamesPlayed": 81,
        "goals": 44,
        "lastName": "Kucherov",
        "otGoals": 1,
        "penaltyMinutes": 22,
        "playerId": 8476453,
        "plusMinus": 8,
        "points": 144,
        "pointsPerGame": 1.77777,
        "positionCode": "R",
        "ppGoals": 13,
        "ppPoints": 53,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.14379,
        "shootsCatches": "L",
        "shots": 306,
        "skaterFullName": "Nikita Kucherov",
        "teamAbbrevs": "TBL",
        "timeOnIcePerGame": 1300.1234
      },
      {
        "assists": 89,
        "evGoals": 41,
        "evPoints": 92,
        "faceoffWinPct": 0.46194,
        "gameWinningGoals": 9,
        "gamesPlayed": 82,
        "goals": 51,
        "lastName": "MacKinnon",
        "otGoals": 2,
        "penaltyMinutes": 42,
        "playerId": 8477492,
        "plusMinus": 35,
        "points": 140,
        "pointsPerGame": 1.70731,
        "positionCode": "C",
        "ppGoals": 10,
        "ppPoints": 48,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.12592,
        "shootsCatches": "R",
        "shots": 405,
        "skaterFullName": "Nathan MacKinnon",
        "teamAbbrevs": "COL",
        "timeOnIcePerGame": 1368.8536
      },
      {
        "assists": 100,
        "evGoals": 24,
        "evPoints": 87,
        "faceoffWinPct": 0.51098,
        "gameWinningGoals": 5,
        "gamesPlayed": 76,
        "goals": 32,
        "lastName": "McDavid",
        "otGoals": 1,
        "penaltyMinutes": 30,
        "playerId": 8478402,
        "plusMinus": 35,
        "points": 132,
        "pointsPerGame": 1.73684,
        "positionCode": "C",
        "ppGoals": 7,
        "ppPoints": 44,
        "seasonId": 20232024,
        "shGoals": 1,
        "shPoints": 1,
        "shootingPct": 0.12167,
        "shootsCatches": "L",
        "shots": 263,
        "skaterFullName": "Connor McDavid",
        "teamAbbrevs": "EDM",
        "timeOnIcePerGame": 1281.5526
      },
      {
        "assists": 71,
        "evGoals": 38,
        "evPoints": 75,
        "faceoffWinPct": 0.1,
        "gameWinningGoals": 5,
        "gamesPlayed": 82,
        "goals": 49,
        "lastName": "Panarin",
        "otGoals": 1,
        "penaltyMinutes": 24,
        "playerId": 8478550,
        "plusMinus": 18,
        "points": 120,
        "pointsPerGame": 1.46341,
        "positionCode": "L",
        "ppGoals": 11,
        "ppPoints": 44,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 1,
        "shootingPct": 0.16225,
        "shootsCatches": "R",
        "shots": 302,
        "skaterFullName": "Artemi Panarin",
        "teamAbbrevs": "NYR",
        "timeOnIcePerGame": 1207.1341
      },
      {
        "assists": 63,
        "evGoals": 35,
        "evPoints": 75,
        "faceoffWinPct": 0.33333,
        "gameWinningGoals": 5,
        "gamesPlayed": 82,
        "goals": 47,
        "lastName": "Pastrnak",
        "otGoals": 0,
        "penaltyMinutes": 47,
        "playerId": 8477956,
        "plusMinus": 21,
        "points": 110,
        "pointsPerGame": 1.34146,
        "positionCode": "R",
        "ppGoals": 12,
        "ppPoints": 35,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.12303,
        "shootsCatches": "R",
        "shots": 382,
        "skaterFullName": "David Pastrnak",
        "teamAbbrevs": "BOS",
        "timeOnIcePerGame": 1195.7804
      },
      {
        "assists": 38,
        "evGoals": 51,
        "evPoints": 77,
        "faceoffWinPct": 0.53449,
        "gameWinningGoals": 8,
        "gamesPlayed": 81,
        "goals": 69,
        "lastName": "Matthews",
        "otGoals": 3,
        "penaltyMinutes": 20,
        "playerId": 8479318,
        "plusMinus": 31,
        "points": 107,
        "pointsPerGame": 1.32098,
        "positionCode": "C",
        "ppGoals": 18,
        "ppPoints": 29,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 1,
        "shootingPct": 0.18699,
        "shootsCatches": "L",
        "shots": 369,
        "skaterFullName": "Auston Matthews",
        "teamAbbrevs": "TOR",
        "timeOnIcePerGame": 1257.9876
      },
      {
        "assists": 65,
        "evGoals": 20,
        "evPoints": 65,
        "faceoffWinPct": 0.56926,
        "gameWinningGoals": 7,
        "gamesPlayed": 81,
        "goals": 41,
        "lastName": "Draisaitl",
        "otGoals": 2,
        "penaltyMinutes": 76,
        "playerId": 8477934,
        "plusMinus": 26,
        "points": 106,
        "pointsPerGame": 1.30864,
        "positionCode": "C",
        "ppGoals": 21,
        "ppPoints": 39,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 2,
        "shootingPct": 0.18894,
        "shootsCatches": "L",
        "shots": 217,
        "skaterFullName": "Leon Draisaitl",
        "teamAbbrevs": "EDM",
        "timeOnIcePerGame": 1241.7283
      },
      {
        "assists": 62,
        "evGoals": 28,
        "evPoints": 64,
        "faceoffWinPct": 0.53816,
        "gameWinningGoals": 9,
        "gamesPlayed": 80,
        "goals": 42,
        "lastName": "Rantanen",
        "otGoals": 0,
        "penaltyMinutes": 50,
        "playerId": 8478420,
        "plusMinus": 19,
        "points": 104,
        "pointsPerGame": 1.3,
        "positionCode": "R",
        "ppGoals": 14,
        "ppPoints": 40,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.15498,
        "shootsCatches": "L",
        "shots": 271,
        "skaterFullName": "Mikko Rantanen",
        "teamAbbrevs": "COL",
        "timeOnIcePerGame": 1374.3375
      },
      {
        "assists": 66,
        "evGoals": 25,
        "evPoints": 61,
        "faceoffWinPct": 0.56331,
        "gameWinningGoals": 9,
        "gamesPlayed": 81,
        "goals": 37,
        "lastName": "Miller",
        "otGoals": 2,
        "penaltyMinutes": 58,
        "playerId": 8476468,
        "plusMinus": 32,
        "points": 103,
        "pointsPerGame": 1.2716,
        "positionCode": "C",
        "ppGoals": 10,
        "ppPoints": 40,
        "seasonId": 20232024,
        "shGoals": 2,
        "shPoints": 2,
        "shootingPct": 0.19072,
        "shootsCatches": "L",
        "shots": 194,
        "skaterFullName": "J.T. Miller",
        "teamAbbrevs": "VAN",
        "timeOnIcePerGame": 1169.395
      },
      {
        "assists": 58,
        "evGoals": 26,
        "evPoints": 59,
        "faceoffWinPct": 0.47058,
        "gameWinningGoals": 7,
        "gamesPlayed": 82,
        "goals": 40,
        "lastName": "Nylander",
        "otGoals": 2,
        "penaltyMinutes": 24,
        "playerId": 8477939,
        "plusMinus": 1,
        "points": 98,
        "pointsPerGame": 1.19512,
        "positionCode": "R",
        "ppGoals": 11,
        "ppPoints": 35,
        "seasonId": 20232024,
        "shGoals": 3,
        "shPoints": 4,
        "shootingPct": 0.12658,
        "shootsCatches": "R",
        "shots": 316,
        "skaterFullName": "William Nylander",
        "teamAbbrevs": "TOR",
        "timeOnIcePerGame": 1194.817
      },
      {
        "assists": 50,
        "evGoals": 27,
        "evPoints": 55,
        "faceoffWinPct": 0,
        "gameWinningGoals": 8,
        "gamesPlayed": 75,
        "goals": 46,
        "lastName": "Kaprizov",
        "otGoals": 2,
        "penaltyMinutes": 36,
        "playerId": 8478864,
        "plusMinus": 11,
        "points": 96,
        "pointsPerGame": 1.28,
        "positionCode": "L",
        "ppGoals": 19,
        "ppPoints": 41,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.16606,
        "shootsCatches": "L",
        "shots": 277,
        "skaterFullName": "Kirill Kaprizov",
        "teamAbbrevs": "MIN",
        "timeOnIcePerGame": 1294.6133
      },
      {
        "assists": 52,
        "evGoals": 32,
        "evPoints": 71,
        "faceoffWinPct": 0.58226,
        "gameWinningGoals": 3,
        "gamesPlayed": 82,
        "goals": 42,
        "lastName": "Crosby",
        "otGoals": 0,
        "penaltyMinutes": 40,
        "playerId": 8471675,
        "plusMinus": 7,
        "points": 94,
        "pointsPerGame": 1.14634,
        "positionCode": "C",
        "ppGoals": 10,
        "ppPoints": 23,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.15107,
        "shootsCatches": "L",
        "shots": 278,
        "skaterFullName": "Sidney Crosby",
        "teamAbbrevs": "PIT",
        "timeOnIcePerGame": 1205.2073
      },
      {
        "assists": 46,
        "evGoals": 35,
        "evPoints": 62,
        "faceoffWinPct": 0.5,
        "gameWinningGoals": 11,
        "gamesPlayed": 82,
        "goals": 48,
        "lastName": "Forsberg",
        "otGoals": 3,
        "penaltyMinutes": 43,
        "playerId": 8476887,
        "plusMinus": 16,
        "points": 94,
        "pointsPerGame": 1.14634,
        "positionCode": "L",
        "ppGoals": 13,
        "ppPoints": 32,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.13832,
        "shootsCatches": "R",
        "shots": 347,
        "skaterFullName": "Filip Forsberg",
        "teamAbbrevs": "NSH",
        "timeOnIcePerGame": 1134.3292
      },
      {
        "assists": 37,
        "evGoals": 25,
        "evPoints": 55,
        "faceoffWinPct": 0.4415,
        "gameWinningGoals": 11,
        "gamesPlayed": 82,
        "goals": 57,
        "lastName": "Reinhart",
        "otGoals": 3,
        "penaltyMinutes": 31,
        "playerId": 8477933,
        "plusMinus": 29,
        "points": 94,
        "pointsPerGame": 1.14634,
        "positionCode": "C",
        "ppGoals": 27,
        "ppPoints": 34,
        "seasonId": 20232024,
        "shGoals": 5,
        "shPoints": 5,
        "shootingPct": 0.24463,
        "shootsCatches": "R",
        "shots": 233,
        "skaterFullName": "Sam Reinhart",
        "teamAbbrevs": "FLA",
        "timeOnIcePerGame": 1217.9878
      },
      {
        "assists": 75,
        "evGoals": 12,
        "evPoints": 54,
        "faceoffWinPct": null,
        "gameWinningGoals": 2,
        "gamesPlayed": 82,
        "goals": 17,
        "lastName": "Hughes",
        "otGoals": 1,
        "penaltyMinutes": 38,
        "playerId": 8480800,
        "plusMinus": 38,
        "points": 92,
        "pointsPerGame": 1.12195,
        "positionCode": "D",
        "ppGoals": 5,
        "ppPoints": 38,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.08542,
        "shootsCatches": "L",
        "shots": 199,
        "skaterFullName": "Quinn Hughes",
        "teamAbbrevs": "VAN",
        "timeOnIcePerGame": 1481.0975
      },
      {
        "assists": 69,
        "evGoals": 13,
        "evPoints": 47,
        "faceoffWinPct": null,
        "gameWinningGoals": 1,
        "gamesPlayed": 77,
        "goals": 21,
        "lastName": "Makar",
        "otGoals": 0,
        "penaltyMinutes": 16,
        "playerId": 8480069,
        "plusMinus": 15,
        "points": 90,
        "pointsPerGame": 1.16883,
        "positionCode": "D",
        "ppGoals": 7,
        "ppPoints": 39,
        "seasonId": 20232024,
        "shGoals": 1,
        "shPoints": 4,
        "shootingPct": 0.0909,
        "shootsCatches": "R",
        "shots": 231,
        "skaterFullName": "Cale Makar",
        "teamAbbrevs": "COL",
        "timeOnIcePerGame": 1486.1818
      },
      {
        "assists": 44,
        "evGoals": 31,
        "evPoints": 58,
        "faceoffWinPct": 0.45652,
        "gameWinningGoals": 12,
        "gamesPlayed": 81,
        "goals": 46,
        "lastName": "Point",
        "otGoals": 0,
        "penaltyMinutes": 14,
        "playerId": 8478010,
        "plusMinus": -16,
        "points": 90,
        "pointsPerGame": 1.11111,
        "positionCode": "C",
        "ppGoals": 15,
        "ppPoints": 32,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.20264,
        "shootsCatches": "R",
        "shots": 227,
        "skaterFullName": "Brayden Point",
        "teamAbbrevs": "TBL",
        "timeOnIcePerGame": 1202.3456
      },
      {
        "assists": 53,
        "evGoals": 24,
        "evPoints": 55,
        "faceoffWinPct": 0.54123,
        "gameWinningGoals": 10,
        "gamesPlayed": 78,
        "goals": 36,
        "lastName": "Aho",
        "otGoals": 2,
        "penaltyMinutes": 36,
        "playerId": 8478427,
        "plusMinus": 34,
        "points": 89,
        "pointsPerGame": 1.14102,
        "positionCode": "C",
        "ppGoals": 11,
        "ppPoints": 32,
        "seasonId": 20232024,
        "shGoals": 1,
        "shPoints": 2,
        "shootingPct": 0.16666,
        "shootsCatches": "L",
        "shots": 216,
        "skaterFullName": "Sebastian Aho",
        "teamAbbrevs": "CAR",
        "timeOnIcePerGame": 1177.6538
      },
      {
        "assists": 55,
        "evGoals": 21,
        "evPoints": 56,
        "faceoffWinPct": 0.50813,
        "gameWinningGoals": 10,
        "gamesPlayed": 82,
        "goals": 34,
        "lastName": "Pettersson",
        "otGoals": 2,
        "penaltyMinutes": 12,
        "playerId": 8480012,
        "plusMinus": 20,
        "points": 89,
        "pointsPerGame": 1.08536,
        "positionCode": "C",
        "ppGoals": 13,
        "ppPoints": 31,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 2,
        "shootingPct": 0.16425,
        "shootsCatches": "L",
        "shots": 207,
        "skaterFullName": "Elias Pettersson",
        "teamAbbrevs": "VAN",
        "timeOnIcePerGame": 1179.0243
      },
      {
        "assists": 62,
        "evGoals": 19,
        "evPoints": 55,
        "faceoffWinPct": 0.33333,
        "gameWinningGoals": 2,
        "gamesPlayed": 80,
        "goals": 26,
        "lastName": "Tkachuk",
        "otGoals": 0,
        "penaltyMinutes": 88,
        "playerId": 8479314,
        "plusMinus": 19,
        "points": 88,
        "pointsPerGame": 1.1,
        "positionCode": "L",
        "ppGoals": 6,
        "ppPoints": 32,
        "seasonId": 20232024,
        "shGoals": 1,
        "shPoints": 1,
        "shootingPct": 0.09285,
        "shootsCatches": "L",
        "shots": 280,
        "skaterFullName": "Matthew Tkachuk",
        "teamAbbrevs": "FLA",
        "timeOnIcePerGame": 1118.4
      },
      {
        "assists": 60,
        "evGoals": 17,
        "evPoints": 56,
        "faceoffWinPct": 0.53123,
        "gameWinningGoals": 3,
        "gamesPlayed": 82,
        "goals": 26,
        "lastName": "Thomas",
        "otGoals": 0,
        "penaltyMinutes": 48,
        "playerId": 8480023,
        "plusMinus": 9,
        "points": 86,
        "pointsPerGame": 1.04878,
        "positionCode": "C",
        "ppGoals": 8,
        "ppPoints": 27,
        "seasonId": 20232024,
        "shGoals": 1,
        "shPoints": 3,
        "shootingPct": 0.15294,
        "shootsCatches": "R",
        "shots": 170,
        "skaterFullName": "Robert Thomas",
        "teamAbbrevs": "STL",
        "timeOnIcePerGame": 1257.9878
      },
      {
        "assists": 59,
        "evGoals": 17,
        "evPoints": 57,
        "faceoffWinPct": 0.25,
        "gameWinningGoals": 2,
        "gamesPlayed": 69,
        "goals": 26,
        "lastName": "Marner",
        "otGoals": 0,
        "penaltyMinutes": 18,
        "playerId": 8478483,
        "plusMinus": 21,
        "points": 85,
        "pointsPerGame": 1.23188,
        "positionCode": "R",
        "ppGoals": 8,
        "ppPoints": 27,
        "seasonId": 20232024,
        "shGoals": 1,
        "shPoints": 1,
        "shootingPct": 0.16455,
        "shootsCatches": "R",
        "shots": 158,
        "skaterFullName": "Mitch Marner",
        "teamAbbrevs": "TOR",
        "timeOnIcePerGame": 1276.5942
      },
      {
        "assists": 62,
        "evGoals": 14,
        "evPoints": 51,
        "faceoffWinPct": null,
        "gameWinningGoals": 5,
        "gamesPlayed": 82,
        "goals": 23,
        "lastName": "Josi",
        "otGoals": 2,
        "penaltyMinutes": 45,
        "playerId": 8474600,
        "plusMinus": 12,
        "points": 85,
        "pointsPerGame": 1.03658,
        "positionCode": "D",
        "ppGoals": 9,
        "ppPoints": 33,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 1,
        "shootingPct": 0.08582,
        "shootsCatches": "L",
        "shots": 268,
        "skaterFullName": "Roman Josi",
        "teamAbbrevs": "NSH",
        "timeOnIcePerGame": 1477.8658
      },
      {
        "assists": 56,
        "evGoals": 20,
        "evPoints": 55,
        "faceoffWinPct": 0.36363,
        "gameWinningGoals": 7,
        "gamesPlayed": 82,
        "goals": 27,
        "lastName": "Bratt",
        "otGoals": 0,
        "penaltyMinutes": 12,
        "playerId": 8479407,
        "plusMinus": -6,
        "points": 83,
        "pointsPerGame": 1.01219,
        "positionCode": "L",
        "ppGoals": 7,
        "ppPoints": 27,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 1,
        "shootingPct": 0.10887,
        "shootsCatches": "L",
        "shots": 248,
        "skaterFullName": "Jesper Bratt",
        "teamAbbrevs": "NJD",
        "timeOnIcePerGame": 1158.439
      },
      {
        "assists": 64,
        "evGoals": 10,
        "evPoints": 47,
        "faceoffWinPct": null,
        "gameWinningGoals": 7,
        "gamesPlayed": 81,
        "goals": 18,
        "lastName": "Bouchard",
        "otGoals": 2,
        "penaltyMinutes": 32,
        "playerId": 8480803,
        "plusMinus": 34,
        "points": 82,
        "pointsPerGame": 1.01234,
        "positionCode": "D",
        "ppGoals": 8,
        "ppPoints": 35,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.08181,
        "shootsCatches": "R",
        "shots": 220,
        "skaterFullName": "Evan Bouchard",
        "teamAbbrevs": "EDM",
        "timeOnIcePerGame": 1379.8271
      },
      {
        "assists": 41,
        "evGoals": 21,
        "evPoints": 42,
        "faceoffWinPct": 0.56043,
        "gameWinningGoals": 6,
        "gamesPlayed": 79,
        "goals": 40,
        "lastName": "Stamkos",
        "otGoals": 0,
        "penaltyMinutes": 34,
        "playerId": 8474564,
        "plusMinus": -21,
        "points": 81,
        "pointsPerGame": 1.02531,
        "positionCode": "C",
        "ppGoals": 19,
        "ppPoints": 39,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.15267,
        "shootsCatches": "R",
        "shots": 262,
        "skaterFullName": "Steven Stamkos",
        "teamAbbrevs": "TBL",
        "timeOnIcePerGame": 1093.7088
      },
      {
        "assists": 57,
        "evGoals": 18,
        "evPoints": 49,
        "faceoffWinPct": 0.57272,
        "gameWinningGoals": 4,
        "gamesPlayed": 73,
        "goals": 23,
        "lastName": "Barkov",
        "otGoals": 0,
        "penaltyMinutes": 24,
        "playerId": 8477493,
        "plusMinus": 33,
        "points": 80,
        "pointsPerGame": 1.09589,
        "positionCode": "C",
        "ppGoals": 5,
        "ppPoints": 29,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 2,
        "shootingPct": 0.11917,
        "shootsCatches": "L",
        "shots": 193,
        "skaterFullName": "Aleksander Barkov",
        "teamAbbrevs": "FLA",
        "timeOnIcePerGame": 1178.2054
      },
      {
        "assists": 57,
        "evGoals": 18,
        "evPoints": 55,
        "faceoffWinPct": 0.42982,
        "gameWinningGoals": 4,
        "gamesPlayed": 80,
        "goals": 23,
        "lastName": "Barzal",
        "otGoals": 2,
        "penaltyMinutes": 34,
        "playerId": 8478445,
        "plusMinus": -4,
        "points": 80,
        "pointsPerGame": 1,
        "positionCode": "C",
        "ppGoals": 5,
        "ppPoints": 25,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.09583,
        "shootsCatches": "R",
        "shots": 240,
        "skaterFullName": "Mathew Barzal",
        "teamAbbrevs": "NYI",
        "timeOnIcePerGame": 1207.95
      },
      {
        "assists": 51,
        "evGoals": 20,
        "evPoints": 52,
        "faceoffWinPct": null,
        "gameWinningGoals": 4,
        "gamesPlayed": 82,
        "goals": 29,
        "lastName": "Robertson",
        "otGoals": 0,
        "penaltyMinutes": 22,
        "playerId": 8480027,
        "plusMinus": 19,
        "points": 80,
        "pointsPerGame": 0.9756,
        "positionCode": "L",
        "ppGoals": 9,
        "ppPoints": 28,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.12554,
        "shootsCatches": "L",
        "shots": 231,
        "skaterFullName": "Jason Robertson",
        "teamAbbrevs": "DAL",
        "timeOnIcePerGame": 1099.4878
      },
      {
        "assists": 47,
        "evGoals": 25,
        "evPoints": 55,
        "faceoffWinPct": 0.26086,
        "gameWinningGoals": 2,
        "gamesPlayed": 67,
        "goals": 30,
        "lastName": "Guentzel",
        "otGoals": 0,
        "penaltyMinutes": 22,
        "playerId": 8477404,
        "plusMinus": 25,
        "points": 77,
        "pointsPerGame": 1.14925,
        "positionCode": "C",
        "ppGoals": 5,
        "ppPoints": 22,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.12605,
        "shootsCatches": "L",
        "shots": 238,
        "skaterFullName": "Jake Guentzel",
        "teamAbbrevs": "PIT,CAR",
        "timeOnIcePerGame": 1201.2388
      },
      {
        "assists": 23,
        "evGoals": 39,
        "evPoints": 57,
        "faceoffWinPct": 0.4375,
        "gameWinningGoals": 7,
        "gamesPlayed": 80,
        "goals": 54,
        "lastName": "Hyman",
        "otGoals": 1,
        "penaltyMinutes": 48,
        "playerId": 8475786,
        "plusMinus": 36,
        "points": 77,
        "pointsPerGame": 0.9625,
        "positionCode": "L",
        "ppGoals": 15,
        "ppPoints": 20,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.1862,
        "shootsCatches": "R",
        "shots": 290,
        "skaterFullName": "Zach Hyman",
        "teamAbbrevs": "EDM",
        "timeOnIcePerGame": 1170.025
      },
      {
        "assists": 52,
        "evGoals": 13,
        "evPoints": 52,
        "faceoffWinPct": 0.58733,
        "gameWinningGoals": 5,
        "gamesPlayed": 82,
        "goals": 25,
        "lastName": "Trocheck",
        "otGoals": 1,
        "penaltyMinutes": 55,
        "playerId": 8476389,
        "plusMinus": 16,
        "points": 77,
        "pointsPerGame": 0.93902,
        "positionCode": "C",
        "ppGoals": 11,
        "ppPoints": 24,
        "seasonId": 20232024,
        "shGoals": 1,
        "shPoints": 1,
        "shootingPct": 0.11627,
        "shootsCatches": "R",
        "shots": 215,
        "skaterFullName": "Vincent Trocheck",
        "teamAbbrevs": "NYR",
        "timeOnIcePerGame": 1287.2804
      },
      {
        "assists": 44,
        "evGoals": 21,
        "evPoints": 46,
        "faceoffWinPct": 0.52555,
        "gameWinningGoals": 1,
        "gamesPlayed": 82,
        "goals": 33,
        "lastName": "Suzuki",
        "otGoals": 1,
        "penaltyMinutes": 36,
        "playerId": 8480018,
        "plusMinus": -14,
        "points": 77,
        "pointsPerGame": 0.93902,
        "positionCode": "C",
        "ppGoals": 12,
        "ppPoints": 31,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.17837,
        "shootsCatches": "R",
        "shots": 185,
        "skaterFullName": "Nick Suzuki",
        "teamAbbrevs": "MTL",
        "timeOnIcePerGame": 1275.8414
      },
      {
        "assists": 63,
        "evGoals": 9,
        "evPoints": 45,
        "faceoffWinPct": null,
        "gameWinningGoals": 2,
        "gamesPlayed": 78,
        "goals": 13,
        "lastName": "Hedman",
        "otGoals": 0,
        "penaltyMinutes": 76,
        "playerId": 8475167,
        "plusMinus": 18,
        "points": 76,
        "pointsPerGame": 0.97435,
        "positionCode": "D",
        "ppGoals": 4,
        "ppPoints": 31,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.07738,
        "shootsCatches": "L",
        "shots": 168,
        "skaterFullName": "Victor Hedman",
        "teamAbbrevs": "TBL",
        "timeOnIcePerGame": 1488.2564
      },
      {
        "assists": 43,
        "evGoals": 24,
        "evPoints": 46,
        "faceoffWinPct": 0.46153,
        "gameWinningGoals": 4,
        "gamesPlayed": 78,
        "goals": 33,
        "lastName": "Keller",
        "otGoals": 0,
        "penaltyMinutes": 32,
        "playerId": 8479343,
        "plusMinus": -20,
        "points": 76,
        "pointsPerGame": 0.97435,
        "positionCode": "R",
        "ppGoals": 9,
        "ppPoints": 30,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.14473,
        "shootsCatches": "L",
        "shots": 228,
        "skaterFullName": "Clayton Keller",
        "teamAbbrevs": "ARI",
        "timeOnIcePerGame": 1154.7435
      },
      {
        "assists": 47,
        "evGoals": 20,
        "evPoints": 44,
        "faceoffWinPct": 0.23076,
        "gameWinningGoals": 4,
        "gamesPlayed": 77,
        "goals": 28,
        "lastName": "Kempe",
        "otGoals": 1,
        "penaltyMinutes": 72,
        "playerId": 8477960,
        "plusMinus": 13,
        "points": 75,
        "pointsPerGame": 0.97402,
        "positionCode": "R",
        "ppGoals": 5,
        "ppPoints": 27,
        "seasonId": 20232024,
        "shGoals": 3,
        "shPoints": 4,
        "shootingPct": 0.11382,
        "shootsCatches": "L",
        "shots": 246,
        "skaterFullName": "Adrian Kempe",
        "teamAbbrevs": "LAK",
        "timeOnIcePerGame": 1136.0389
      },
      {
        "assists": 52,
        "evGoals": 17,
        "evPoints": 49,
        "faceoffWinPct": 0.38461,
        "gameWinningGoals": 4,
        "gamesPlayed": 81,
        "goals": 23,
        "lastName": "Nyquist",
        "otGoals": 0,
        "penaltyMinutes": 8,
        "playerId": 8474679,
        "plusMinus": 7,
        "points": 75,
        "pointsPerGame": 0.92592,
        "positionCode": "C",
        "ppGoals": 5,
        "ppPoints": 24,
        "seasonId": 20232024,
        "shGoals": 1,
        "shPoints": 2,
        "shootingPct": 0.15032,
        "shootsCatches": "L",
        "shots": 153,
        "skaterFullName": "Gustav Nyquist",
        "teamAbbrevs": "NSH",
        "timeOnIcePerGame": 1064.5432
      },
      {
        "assists": 46,
        "evGoals": 19,
        "evPoints": 53,
        "faceoffWinPct": 0.48925,
        "gameWinningGoals": 4,
        "gamesPlayed": 82,
        "goals": 29,
        "lastName": "Kadri",
        "otGoals": 2,
        "penaltyMinutes": 43,
        "playerId": 8475172,
        "plusMinus": 0,
        "points": 75,
        "pointsPerGame": 0.91463,
        "positionCode": "C",
        "ppGoals": 10,
        "ppPoints": 22,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.10469,
        "shootsCatches": "L",
        "shots": 277,
        "skaterFullName": "Nazem Kadri",
        "teamAbbrevs": "CGY",
        "timeOnIcePerGame": 1105.5487
      },
      {
        "assists": 36,
        "evGoals": 19,
        "evPoints": 41,
        "faceoffWinPct": 0.36458,
        "gameWinningGoals": 7,
        "gamesPlayed": 82,
        "goals": 39,
        "lastName": "Kreider",
        "otGoals": 1,
        "penaltyMinutes": 26,
        "playerId": 8475184,
        "plusMinus": 19,
        "points": 75,
        "pointsPerGame": 0.91463,
        "positionCode": "L",
        "ppGoals": 18,
        "ppPoints": 29,
        "seasonId": 20232024,
        "shGoals": 2,
        "shPoints": 5,
        "shootingPct": 0.15853,
        "shootsCatches": "L",
        "shots": 246,
        "skaterFullName": "Chris Kreider",
        "teamAbbrevs": "NYR",
        "timeOnIcePerGame": 1127.0121
      },
      {
        "assists": 49,
        "evGoals": 24,
        "evPoints": 66,
        "faceoffWinPct": 0.40983,
        "gameWinningGoals": 3,
        "gamesPlayed": 82,
        "goals": 26,
        "lastName": "Hagel",
        "otGoals": 1,
        "penaltyMinutes": 79,
        "playerId": 8479542,
        "plusMinus": 1,
        "points": 75,
        "pointsPerGame": 0.91463,
        "positionCode": "L",
        "ppGoals": 2,
        "ppPoints": 7,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 2,
        "shootingPct": 0.1413,
        "shootsCatches": "L",
        "shots": 184,
        "skaterFullName": "Brandon Hagel",
        "teamAbbrevs": "TBL",
        "timeOnIcePerGame": 1155.3536
      },
      {
        "assists": 47,
        "evGoals": 18,
        "evPoints": 43,
        "faceoffWinPct": 0.37223,
        "gameWinningGoals": 4,
        "gamesPlayed": 62,
        "goals": 27,
        "lastName": "Hughes",
        "otGoals": 2,
        "penaltyMinutes": 12,
        "playerId": 8481559,
        "plusMinus": -12,
        "points": 74,
        "pointsPerGame": 1.19354,
        "positionCode": "C",
        "ppGoals": 9,
        "ppPoints": 31,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.09854,
        "shootsCatches": "L",
        "shots": 274,
        "skaterFullName": "Jack Hughes",
        "teamAbbrevs": "NJD",
        "timeOnIcePerGame": 1258.4354
      },
      {
        "assists": 37,
        "evGoals": 25,
        "evPoints": 52,
        "faceoffWinPct": 0.52631,
        "gameWinningGoals": 2,
        "gamesPlayed": 81,
        "goals": 37,
        "lastName": "Tkachuk",
        "otGoals": 1,
        "penaltyMinutes": 134,
        "playerId": 8480801,
        "plusMinus": 1,
        "points": 74,
        "pointsPerGame": 0.91358,
        "positionCode": "L",
        "ppGoals": 12,
        "ppPoints": 22,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.10364,
        "shootsCatches": "L",
        "shots": 357,
        "skaterFullName": "Brady Tkachuk",
        "teamAbbrevs": "OTT",
        "timeOnIcePerGame": 1148.5308
      },
      {
        "assists": 56,
        "evGoals": 10,
        "evPoints": 38,
        "faceoffWinPct": null,
        "gameWinningGoals": 5,
        "gamesPlayed": 72,
        "goals": 17,
        "lastName": "Fox",
        "otGoals": 1,
        "penaltyMinutes": 36,
        "playerId": 8479323,
        "plusMinus": 21,
        "points": 73,
        "pointsPerGame": 1.01388,
        "positionCode": "D",
        "ppGoals": 6,
        "ppPoints": 33,
        "seasonId": 20232024,
        "shGoals": 1,
        "shPoints": 2,
        "shootingPct": 0.12408,
        "shootsCatches": "R",
        "shots": 137,
        "skaterFullName": "Adam Fox",
        "teamAbbrevs": "NYR",
        "timeOnIcePerGame": 1406.6111
      },
      {
        "assists": 33,
        "evGoals": 24,
        "evPoints": 48,
        "faceoffWinPct": 0.52,
        "gameWinningGoals": 4,
        "gamesPlayed": 81,
        "goals": 40,
        "lastName": "Boeser",
        "otGoals": 1,
        "penaltyMinutes": 14,
        "playerId": 8478444,
        "plusMinus": 23,
        "points": 73,
        "pointsPerGame": 0.90123,
        "positionCode": "R",
        "ppGoals": 16,
        "ppPoints": 25,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.19607,
        "shootsCatches": "R",
        "shots": 204,
        "skaterFullName": "Brock Boeser",
        "teamAbbrevs": "VAN",
        "timeOnIcePerGame": 1116.1358
      },
      {
        "assists": 44,
        "evGoals": 18,
        "evPoints": 43,
        "faceoffWinPct": 0.26315,
        "gameWinningGoals": 2,
        "gamesPlayed": 82,
        "goals": 29,
        "lastName": "Fiala",
        "otGoals": 1,
        "penaltyMinutes": 62,
        "playerId": 8477942,
        "plusMinus": 1,
        "points": 73,
        "pointsPerGame": 0.89024,
        "positionCode": "L",
        "ppGoals": 11,
        "ppPoints": 30,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.12888,
        "shootsCatches": "L",
        "shots": 225,
        "skaterFullName": "Kevin Fiala",
        "teamAbbrevs": "LAK",
        "timeOnIcePerGame": 1082.1341
      },
      {
        "assists": 47,
        "evGoals": 19,
        "evPoints": 54,
        "faceoffWinPct": 0.48124,
        "gameWinningGoals": 4,
        "gamesPlayed": 74,
        "goals": 25,
        "lastName": "Scheifele",
        "otGoals": 1,
        "penaltyMinutes": 57,
        "playerId": 8476460,
        "plusMinus": 19,
        "points": 72,
        "pointsPerGame": 0.97297,
        "positionCode": "C",
        "ppGoals": 6,
        "ppPoints": 18,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.16233,
        "shootsCatches": "R",
        "shots": 154,
        "skaterFullName": "Mark Scheifele",
        "teamAbbrevs": "WPG",
        "timeOnIcePerGame": 1211.1351
      },
      {
        "assists": 38,
        "evGoals": 26,
        "evPoints": 51,
        "faceoffWinPct": 0.44047,
        "gameWinningGoals": 7,
        "gamesPlayed": 76,
        "goals": 34,
        "lastName": "Verhaeghe",
        "otGoals": 1,
        "penaltyMinutes": 36,
        "playerId": 8477409,
        "plusMinus": 17,
        "points": 72,
        "pointsPerGame": 0.94736,
        "positionCode": "C",
        "ppGoals": 8,
        "ppPoints": 21,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.13821,
        "shootsCatches": "L",
        "shots": 246,
        "skaterFullName": "Carter Verhaeghe",
        "teamAbbrevs": "FLA",
        "timeOnIcePerGame": 1077.75
      },
      {
        "assists": 46,
        "evGoals": 12,
        "evPoints": 35,
        "faceoffWinPct": 0.4928,
        "gameWinningGoals": 3,
        "gamesPlayed": 81,
        "goals": 26,
        "lastName": "Zibanejad",
        "otGoals": 2,
        "penaltyMinutes": 30,
        "playerId": 8476459,
        "plusMinus": 15,
        "points": 72,
        "pointsPerGame": 0.88888,
        "positionCode": "C",
        "ppGoals": 12,
        "ppPoints": 31,
        "seasonId": 20232024,
        "shGoals": 2,
        "shPoints": 6,
        "shootingPct": 0.11764,
        "shootsCatches": "R",
        "shots": 221,
        "skaterFullName": "Mika Zibanejad",
        "teamAbbrevs": "NYR",
        "timeOnIcePerGame": 1184.6296
      },
      {
        "assists": 41,
        "evGoals": 25,
        "evPoints": 56,
        "faceoffWinPct": 0.4,
        "gameWinningGoals": 4,
        "gamesPlayed": 82,
        "goals": 31,
        "lastName": "Raymond",
        "otGoals": 3,
        "penaltyMinutes": 30,
        "playerId": 8482078,
        "plusMinus": -12,
        "points": 72,
        "pointsPerGame": 0.87804,
        "positionCode": "L",
        "ppGoals": 6,
        "ppPoints": 16,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.19018,
        "shootsCatches": "R",
        "shots": 163,
        "skaterFullName": "Lucas Raymond",
        "teamAbbrevs": "DET",
        "timeOnIcePerGame": 1065.1951
      },
      {
        "assists": 52,
        "evGoals": 17,
        "evPoints": 50,
        "faceoffWinPct": 0.46679,
        "gameWinningGoals": 2,
        "gamesPlayed": 75,
        "goals": 18,
        "lastName": "Stützle",
        "otGoals": 2,
        "penaltyMinutes": 28,
        "playerId": 8482116,
        "plusMinus": -17,
        "points": 70,
        "pointsPerGame": 0.93333,
        "positionCode": "C",
        "ppGoals": 1,
        "ppPoints": 20,
        "seasonId": 20232024,
        "shGoals": 0,
        "shPoints": 0,
        "shootingPct": 0.09375,
        "shootsCatches": "L",
        "shots": 192,
        "skaterFullName": "Tim Stützle",
        "teamAbbrevs": "OTT",
        "timeOnIcePerGame": 1267.1066
      }
    ]

    let scorers = data.filter(player => position === 'all' || player.positionCode === position)
    .sort((a,b) => {
      if (a[sort] > b[sort]) {
        return -1;
      } else if (a[sort] < b[sort]) {
        return 1;
      }
      return 0;
    })
    .map(player => {
      return {
        label: `${player.skaterFullName}`,
        values: [player.goals, player.assists, player.points]
      }})

    const maxValue = data[0].points

    return { json: { chartData: { maxValue, scorers } } }
}
